In [21]:
import sqlite3
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [22]:
def make_query(query, filepath='database.sqlite'):
    """
    Execute a query on a SQLite database file and return the results as a pandas DataFrame.

    Parameters
    ----------
    query : str
        SQL query to be executed on the database file.
    filepath : str, optional
        Path to the database file, by default 'database.sqlite'.

    Returns
    -------
    pd.DataFrame
        A pandas DataFrame containing the results of the executed query.
    """
    with sqlite3.connect(filepath) as connection:
        cursor = connection.cursor()
        execution = cursor.execute(query)
        result = pd.DataFrame(execution.fetchall(), columns=[i[0] for i in execution.description])
        return result

In [35]:
player_rating = make_query(
"""
SELECT pl.player_name
       , ROUND(AVG(att.potential + att.crossing + att.finishing + att.heading_accuracy
       + att.short_passing + att.volleys + att.dribbling + att.curve 
       + att.free_kick_accuracy + att.long_passing + att.ball_control 
       + att.acceleration + att.sprint_speed + att.agility + att.reactions 
       + att.balance + att.shot_power + att.jumping + att.stamina + att.strength 
       + att.long_shots + att.aggression + att.interceptions + att.positioning 
       + att.vision + att.penalties + att.marking + att.standing_tackle + att.sliding_tackle 
       + att.gk_diving + att.gk_handling + att.gk_kicking + att.gk_positioning + att.gk_reflexes) / 33,0) AS avg_all_columns
FROM player AS pl
INNER JOIN player_attributes AS att
ON pl.player_api_id = att.player_api_id

GROUP BY pl.player_name

""")

player_rating

                       player_name  avg_all_columns
0               Aaron Appindangoye             50.0
1                  Aaron Cresswell             58.0
2                      Aaron Doran             55.0
3                    Aaron Galindo             52.0
4                     Aaron Hughes             52.0
...                            ...              ...
10843                    Zsolt Low             58.0
10844          Zurab Khizanishvili             56.0
10845           Zvjezdan Misimovic             63.0
10846  de Oliveira Cleber Monteiro             57.0
10847      dos Santos Fabio Junior             57.0

[10848 rows x 2 columns]

In [34]:
player_attributes = make_query(
"""
SELECT pl.player_api_id
      ,pl.player_namE
      ,att.overall_rating
       
FROM player AS pl
INNER JOIN player_attributes AS att
ON pl.player_api_id = att.player_api_id

GROUP BY pl.player_name


""")

player_attributes

       player_api_id                  player_name  overall_rating
0             505942           Aaron Appindangoye              67
1             155782              Aaron Cresswell              74
2             162549                  Aaron Doran              65
3              30572                Aaron Galindo              69
4              23780                 Aaron Hughes              70
...              ...                          ...             ...
10843          36491                    Zsolt Low              68
10844          35506          Zurab Khizanishvili              67
10845          39902           Zvjezdan Misimovic              78
10846          11833  de Oliveira Cleber Monteiro              62
10847          38804      dos Santos Fabio Junior              70

[10848 rows x 3 columns]

In [13]:
player_attributes2 = make_query(
"""
SELECT *
       
FROM player_attributes


""")

player_attributes2

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,71.0,70.0,45.0,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,71.0,70.0,45.0,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,63.0,41.0,45.0,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,63.0,48.0,60.0,64.0,59.0,46.0,65.0,54.0,58.0,54.0,76.0,34.0,62.0,40.0,44.0,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,63.0,48.0,60.0,64.0,59.0,46.0,65.0,54.0,58.0,54.0,76.0,34.0,62.0,40.0,44.0,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183974,102359,39902,2009-08-30 00:00:00,83.0,85.0,right,medium,low,84.0,77.0,59.0,89.0,77.0,84.0,86.0,78.0,84.0,85.0,66.0,72.0,77.0,86.0,73.0,76.0,58.0,72.0,67.0,81.0,56.0,78.0,86.0,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183975,102359,39902,2009-02-22 00:00:00,78.0,80.0,right,medium,low,74.0,76.0,53.0,84.0,77.0,85.0,86.0,74.0,73.0,86.0,66.0,67.0,77.0,74.0,73.0,75.0,58.0,66.0,65.0,73.0,61.0,64.0,72.0,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183976,102359,39902,2008-08-30 00:00:00,77.0,80.0,right,medium,low,74.0,71.0,53.0,84.0,77.0,85.0,86.0,74.0,73.0,86.0,66.0,67.0,77.0,74.0,73.0,75.0,58.0,66.0,65.0,73.0,67.0,64.0,72.0,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183977,102359,39902,2007-08-30 00:00:00,78.0,81.0,right,medium,low,74.0,64.0,57.0,86.0,77.0,87.0,86.0,73.0,73.0,91.0,61.0,60.0,77.0,69.0,73.0,72.0,58.0,67.0,59.0,78.0,63.0,63.0,68.0,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183978,102359,39902,2007-02-22 00:00:00,80.0,81.0,right,medium,low,74.0,68.0,57.0,88.0,77.0,87.0,86.0,53.0,78.0,91.0,58.0,64.0,77.0,66.0,73.0,72.0,58.0,67.0,59.0,78.0,63.0,63.0,68.0,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0